from typing import Dict, Any, List, Optional

class BrokerBase:
    def account_equity(self) -> float: ...
    def positions(self) -> Dict[str, float]: ...
    def open_orders(self) -> List[Dict[str, Any]]: ...
    def submit_bracket(self, symbol: str, qty: int, side: str, entry_price: float, take_profit: float, stop_price: float, client_order_id: str) -> Any: ...
    def cancel_all(self) -> None: ...
    def close_position(self, symbol: str) -> None: ...
    def recent_fills(self, limit: int = 100) -> List[Dict[str, Any]]: ...
    def lockout_today(self) -> bool: ...

