name: Daily Report (Self-Hosted)

on:
  workflow_dispatch:
  schedule:
    # ~16:10 ET during Daylight Time (20:10 UTC). Adjust for DST if needed.
    - cron: "10 20 * * 1-5"

permissions:
  contents: read

concurrency:
  group: daily-report
  cancel-in-progress: true

jobs:
  report:
    runs-on: [self-hosted, windows]
    env:
      PYTHONPATH: ${{ github.workspace }}
      ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
      ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
      APCA_BASE_URL: ${{ vars.APCA_BASE_URL }}
      TICKERS: ${{ vars.TICKERS }}
      CONFIG_PATH: ${{ vars.CONFIG_PATH }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Python
        run: |
          whoami
          python --version
          where python

      - name: Install deps (binary wheels only)
        env:
          PIP_ONLY_BINARY: ":all:"
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --only-binary=:all: -r requirements.txt

      - name: Generate daily report
        run: |
          python scripts/daily_report.py --config "${{ env.CONFIG_PATH }}"

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: reports/
